name: sweetcafe
description: "Cafe"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  go_router: ^9.0.0
  get_it: ^8.0.2
  http: ^0.13.3
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  cupertino_icons: ^1.0.8
  json_annotation: ^4.4.0
  json_serializable: ^6.0.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true








